### PR TITLE
Add flag for enabling non-default checks

### PR DESCRIPTION
**Pull request by devinsba**
Adds a config to allow some languages to use checks that are not enabled by default. Unblocks #127

### CODE REVIEW

**Review by wconti27 — APPROVED** [review]
Looks good thanks!

**Review by Kyle-Verhoog — COMMENTED** [review]
Can we please add tests + docs to the README as well

**Comment by devinsba** [comment]
Working on tests, can I just modify the existing release note file to get that check to pass?

**Comment by Kyle-Verhoog** [comment]
there is the `no-changelog` github label for when a release note isn't needed

**Pull request merged**
